"""Seed script to populate the database with sample data for demonstration."""
import asyncio
import random
from datetime import datetime, timedelta
from app.database import init_db, async_session
from app.models.convocatoria import Convocatoria
from app.utils.helpers import generate_hash

SAMPLE_DATA = [
    {
        "titulo": "Convocatoria Nacional de Proyectos de I+D+i en Energías Renovables",
        "descripcion": "Minciencias convoca a grupos de investigación para presentar proyectos de investigación, desarrollo e innovación en energías renovables y transición energética. Se buscan propuestas que contribuyan a la diversificación de la matriz energética de Colombia.",
        "entidad": "Minciencias",
        "pais": "Colombia",
        "region": "América Latina",
        "sector": "Ciencia y Tecnología",
        "tipo": "investigación",
        "estado": "abierta",
        "fecha_publicacion": datetime(2026, 1, 15),
        "fecha_apertura": datetime(2026, 2, 1),
        "fecha_cierre": datetime(2026, 6, 30),
        "monto_minimo": 50000000,
        "monto_maximo": 200000000,
        "moneda": "COP",
        "url_fuente": "https://minciencias.gov.co/convocatorias/energias-renovables-2026",
        "requisitos": "Grupos de investigación categoría A o B en Minciencias. Instituciones de educación superior acreditadas.",
        "beneficiarios": "Universidades, centros de investigación y empresas del sector energético.",
        "tags": "energías renovables,investigación,transición energética,Colombia",
        "fuente_scraping": "Minciencias Colombia",
    },
    {
        "titulo": "Fondo Emprender - Convocatoria Nacional 2026",
        "descripcion": "El SENA a través del Fondo Emprender abre convocatoria para financiar iniciativas empresariales de aprendices, practicantes, recién egresados y profesionales con ideas de negocio innovadoras.",
        "entidad": "SENA - Fondo Emprender",
        "pais": "Colombia",
        "region": "América Latina",
        "sector": "Emprendimiento",
        "tipo": "emprendimiento",
        "estado": "abierta",
        "fecha_publicacion": datetime(2026, 1, 10),
        "fecha_apertura": datetime(2026, 1, 20),
        "fecha_cierre": datetime(2026, 5, 15),
        "monto_minimo": 20000000,
        "monto_maximo": 80000000,
        "moneda": "COP",
        "url_fuente": "https://www.fondoemprender.com/convocatorias/2026",
        "requisitos": "Aprendices SENA, universitarios o egresados con plan de negocio estructurado.",
        "beneficiarios": "Emprendedores colombianos entre 18 y 35 años.",
        "tags": "emprendimiento,sena,fondo emprender,startups,Colombia",
        "fuente_scraping": "SENA Fondo Emprender",
    },
    {
        "titulo": "Horizon Europe - Cluster 4: Digital, Industry and Space",
        "descripcion": "The European Commission invites proposals for collaborative research and innovation projects in digital technologies, manufacturing, and space applications. Focus on AI, cybersecurity, and advanced manufacturing.",
        "entidad": "Comisión Europea",
        "pais": "Unión Europea",
        "region": "Europa",
        "sector": "Investigación e Innovación",
        "tipo": "investigación",
        "estado": "abierta",
        "fecha_publicacion": datetime(2025, 12, 1),
        "fecha_apertura": datetime(2026, 1, 15),
        "fecha_cierre": datetime(2026, 9, 20),
        "monto_minimo": 500000,
        "monto_maximo": 5000000,
        "moneda": "EUR",
        "url_fuente": "https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-details/horizon-cl4-2026",
        "requisitos": "Consorcio mínimo de 3 entidades de 3 países diferentes de la UE o asociados.",
        "beneficiarios": "Universidades, centros de investigación, empresas y pymes europeas.",
        "tags": "horizonte europa,investigación,innovación,digital,IA,Europa",
        "fuente_scraping": "EU Funding & Tenders",
    },
    {
        "titulo": "iNNpulsa - Programa Aldea: Aceleración de Emprendimientos de Alto Impacto",
        "descripcion": "Programa de aceleración para emprendimientos colombianos con potencial de crecimiento exponencial. Incluye mentoría, acompañamiento técnico y financiamiento semilla.",
        "entidad": "iNNpulsa Colombia",
        "pais": "Colombia",
        "region": "América Latina",
        "sector": "Emprendimiento",
        "tipo": "emprendimiento",
        "estado": "abierta",
        "fecha_publicacion": datetime(2026, 2, 1),
        "fecha_apertura": datetime(2026, 2, 15),
        "fecha_cierre": datetime(2026, 4, 30),
        "monto_minimo": 30000000,
        "monto_maximo": 120000000,
        "moneda": "COP",
        "url_fuente": "https://www.innpulsa.gov.co/aldea-2026",
        "requisitos": "Emprendimientos con producto mínimo viable (MVP) y tracción inicial demostrable.",
        "beneficiarios": "Startups y emprendimientos de alto impacto en Colombia.",
        "tags": "aceleración,emprendimiento,innpulsa,aldea,Colombia",
        "fuente_scraping": "iNNpulsa Colombia",
    },
    {
        "titulo": "World Bank Innovation Fund - Latin America & Caribbean",
        "descripcion": "The World Bank Group launches a competitive innovation fund to support transformative solutions addressing development challenges in Latin America and the Caribbean region.",
        "entidad": "Banco Mundial",
        "pais": "Internacional",
        "region": "Internacional",
        "sector": "Desarrollo",
        "tipo": "desarrollo",
        "estado": "abierta",
        "fecha_publicacion": datetime(2026, 1, 5),
        "fecha_apertura": datetime(2026, 2, 1),
        "fecha_cierre": datetime(2026, 7, 31),
        "monto_minimo": 100000,
        "monto_maximo": 2000000,
        "moneda": "USD",
        "url_fuente": "https://www.worldbank.org/en/programs/innovation-fund-lac-2026",
        "requisitos": "Organizaciones registradas en países de LAC. Propuestas en inglés o español.",
        "beneficiarios": "ONGs, gobiernos locales, empresas sociales y centros de investigación.",
        "tags": "banco mundial,desarrollo,innovación,LAC,internacional",
        "fuente_scraping": "Banco Mundial",
    },
    {
        "titulo": "Convocatoria de Transferencia Tecnológica Universidad-Empresa",
        "descripcion": "Minciencias promueve la articulación entre academia y sector productivo para transferir resultados de investigación al mercado. Financiamiento para prototipos, patentes y escalamiento.",
        "entidad": "Minciencias",
        "pais": "Colombia",
        "region": "América Latina",
        "sector": "Ciencia y Tecnología",
        "tipo": "transferencia_tecnológica",
        "estado": "próxima",
        "fecha_publicacion": datetime(2026, 3, 1),
        "fecha_apertura": datetime(2026, 4, 1),
        "fecha_cierre": datetime(2026, 8, 15),
        "monto_minimo": 100000000,
        "monto_maximo": 500000000,
        "moneda": "COP",
        "url_fuente": "https://minciencias.gov.co/convocatorias/transferencia-tecnologica-2026",
        "requisitos": "Alianza entre al menos una universidad y una empresa del sector productivo.",
        "beneficiarios": "Alianzas universidad-empresa en Colombia.",
        "tags": "transferencia tecnológica,universidad,empresa,patentes,Colombia",
        "fuente_scraping": "Minciencias Colombia",
    },
    {
        "titulo": "EIT Digital Innovation Activities 2026",
        "descripcion": "EIT Digital invites proposals for pan-European innovation activities focusing on digital technology, health tech, smart cities, and fintech. Support for scaling deep tech ventures.",
        "entidad": "EIT Digital",
        "pais": "Unión Europea",
        "region": "Europa",
        "sector": "Innovación Digital",
        "tipo": "innovación",
        "estado": "abierta",
        "fecha_publicacion": datetime(2025, 11, 15),
        "fecha_apertura": datetime(2026, 1, 10),
        "fecha_cierre": datetime(2026, 5, 30),
        "monto_minimo": 200000,
        "monto_maximo": 1500000,
        "moneda": "EUR",
        "url_fuente": "https://www.eitdigital.eu/innovation/activities-2026",
        "requisitos": "Consorcios pan-europeos con al menos un partner KIC.",
        "beneficiarios": "Empresas tecnológicas, universidades y centros de innovación europeos.",
        "tags": "EIT,digital,innovación,deep tech,fintech,Europa",
        "fuente_scraping": "EU Funding & Tenders",
    },
    {
        "titulo": "Programa de Cooperación Internacional Colombia-Alemania en CTI",
        "descripcion": "Programa bilateral de cooperación para el fomento de la ciencia, tecnología e innovación entre Colombia y Alemania. Financia movilidades, proyectos conjuntos y seminarios.",
        "entidad": "DAAD / Minciencias",
        "pais": "Colombia",
        "region": "América Latina",
        "sector": "Cooperación Internacional",
        "tipo": "cooperación_internacional",
        "estado": "abierta",
        "fecha_publicacion": datetime(2026, 2, 10),
        "fecha_apertura": datetime(2026, 3, 1),
        "fecha_cierre": datetime(2026, 6, 15),
        "monto_minimo": 20000,
        "monto_maximo": 150000,
        "moneda": "EUR",
        "url_fuente": "https://minciencias.gov.co/convocatorias/cooperacion-colombia-alemania",
        "requisitos": "Investigadores vinculados a instituciones colombianas y alemanas.",
        "beneficiarios": "Investigadores y grupos de investigación de ambos países.",
        "tags": "cooperación,Alemania,DAAD,investigación,movilidad,Colombia",
        "fuente_scraping": "Minciencias Colombia",
    },
    {
        "titulo": "Regalías para CTeI - Convocatoria Departamental 2026",
        "descripcion": "Financiamiento con recursos del Sistema General de Regalías para proyectos de ciencia, tecnología e innovación de impacto regional en todos los departamentos de Colombia.",
        "entidad": "DNP / SGR",
        "pais": "Colombia",
        "region": "América Latina",
        "sector": "Ciencia y Tecnología",
        "tipo": "investigación",
        "estado": "abierta",
        "fecha_publicacion": datetime(2026, 1, 20),
        "fecha_apertura": datetime(2026, 2, 15),
        "fecha_cierre": datetime(2026, 7, 20),
        "monto_minimo": 500000000,
        "monto_maximo": 5000000000,
        "moneda": "COP",
        "url_fuente": "https://www.sgr.gov.co/convocatorias/ctei-2026",
        "requisitos": "Gobernaciones y alcaldías en alianza con universidades y centros de investigación.",
        "beneficiarios": "Departamentos y municipios de Colombia.",
        "tags": "regalías,CTeI,departamental,regional,Colombia",
        "fuente_scraping": "Minciencias Colombia",
    },
    {
        "titulo": "USAID Innovation Challenge - Climate & Agriculture",
        "descripcion": "USAID launches an innovation challenge seeking scalable solutions for climate-resilient agriculture in developing countries, with focus on Central and South America.",
        "entidad": "USAID",
        "pais": "Estados Unidos",
        "region": "Internacional",
        "sector": "Desarrollo",
        "tipo": "innovación",
        "estado": "abierta",
        "fecha_publicacion": datetime(2026, 2, 5),
        "fecha_apertura": datetime(2026, 3, 1),
        "fecha_cierre": datetime(2026, 8, 30),
        "monto_minimo": 50000,
        "monto_maximo": 500000,
        "moneda": "USD",
        "url_fuente": "https://www.usaid.gov/innovation/climate-agriculture-2026",
        "requisitos": "Organizaciones registradas con experiencia en agricultura sostenible.",
        "beneficiarios": "ONGs, empresas sociales, cooperativas agrícolas en América Latina.",
        "tags": "USAID,clima,agricultura,innovación,América Latina",
        "fuente_scraping": "Banco Mundial",
    },
    {
        "titulo": "Colciencias Jóvenes Investigadores e Innovadores 2026",
        "descripcion": "Becas-pasantía para jóvenes profesionales y estudiantes de maestría que deseen vincularse a grupos de investigación reconocidos por Minciencias.",
        "entidad": "Minciencias",
        "pais": "Colombia",
        "region": "América Latina",
        "sector": "Ciencia y Tecnología",
        "tipo": "investigación",
        "estado": "próxima",
        "fecha_publicacion": datetime(2026, 3, 15),
        "fecha_apertura": datetime(2026, 4, 15),
        "fecha_cierre": datetime(2026, 6, 30),
        "monto_minimo": 2000000,
        "monto_maximo": 5000000,
        "moneda": "COP",
        "url_fuente": "https://minciencias.gov.co/convocatorias/jovenes-investigadores-2026",
        "requisitos": "Jóvenes entre 18 y 28 años, estudiantes o recién egresados de pregrado o maestría.",
        "beneficiarios": "Jóvenes investigadores colombianos.",
        "tags": "jóvenes,investigadores,becas,Minciencias,Colombia",
        "fuente_scraping": "Minciencias Colombia",
    },
    {
        "titulo": "Convocatoria Apps.co - Fase de Descubrimiento",
        "descripcion": "iNNpulsa y MinTIC abren la fase de descubrimiento del programa Apps.co para emprendimientos digitales. Formación, mentoría y recursos para validar modelos de negocio digitales.",
        "entidad": "iNNpulsa Colombia / MinTIC",
        "pais": "Colombia",
        "region": "América Latina",
        "sector": "Emprendimiento",
        "tipo": "emprendimiento",
        "estado": "abierta",
        "fecha_publicacion": datetime(2026, 2, 20),
        "fecha_apertura": datetime(2026, 3, 5),
        "fecha_cierre": datetime(2026, 5, 20),
        "monto_minimo": 0,
        "monto_maximo": 50000000,
        "moneda": "COP",
        "url_fuente": "https://apps.co/convocatorias/descubrimiento-2026",
        "requisitos": "Equipos de 2 a 5 personas con idea de negocio digital.",
        "beneficiarios": "Emprendedores digitales en Colombia.",
        "tags": "apps.co,digital,emprendimiento,MinTIC,Colombia",
        "fuente_scraping": "iNNpulsa Colombia",
    },
    {
        "titulo": "Global Innovation Fund - Emerging Technologies for Development",
        "descripcion": "GIF supports innovations that aim to improve the lives and opportunities of millions of people in the developing world. Focus on edtech, healthtech, and fintech solutions.",
        "entidad": "Global Innovation Fund",
        "pais": "Reino Unido",
        "region": "Internacional",
        "sector": "Desarrollo",
        "tipo": "innovación",
        "estado": "abierta",
        "fecha_publicacion": datetime(2026, 1, 8),
        "fecha_apertura": datetime(2026, 2, 1),
        "fecha_cierre": datetime(2026, 12, 31),
        "monto_minimo": 50000,
        "monto_maximo": 15000000,
        "moneda": "USD",
        "url_fuente": "https://www.globalinnovation.fund/apply/emerging-tech-2026",
        "requisitos": "Innovaciones con evidencia de impacto en países en desarrollo.",
        "beneficiarios": "Empresas sociales, startups y ONGs a nivel mundial.",
        "tags": "GIF,innovación,desarrollo,edtech,healthtech,fintech",
        "fuente_scraping": "Banco Mundial",
    },
    {
        "titulo": "BID Lab - Convocatoria de Innovación Social para América Latina",
        "descripcion": "El laboratorio de innovación del BID busca proyectos transformadores que utilicen tecnología para resolver desafíos sociales en América Latina y el Caribe.",
        "entidad": "BID Lab",
        "pais": "Internacional",
        "region": "América Latina",
        "sector": "Innovación Social",
        "tipo": "innovación",
        "estado": "abierta",
        "fecha_publicacion": datetime(2026, 2, 12),
        "fecha_apertura": datetime(2026, 3, 1),
        "fecha_cierre": datetime(2026, 9, 15),
        "monto_minimo": 150000,
        "monto_maximo": 1500000,
        "moneda": "USD",
        "url_fuente": "https://bidlab.org/convocatorias/innovacion-social-2026",
        "requisitos": "Organizaciones establecidas en LAC con al menos 2 años de operación.",
        "beneficiarios": "Empresas sociales, ONGs y startups en América Latina.",
        "tags": "BID Lab,innovación social,tecnología,LAC,impacto social",
        "fuente_scraping": "Banco Mundial",
    },
    {
        "titulo": "Erasmus+ KA2 - Strategic Partnerships for Higher Education",
        "descripcion": "Erasmus+ finances cooperation partnerships between higher education institutions to modernize teaching, develop joint curricula, and strengthen international collaboration.",
        "entidad": "Comisión Europea - EACEA",
        "pais": "Unión Europea",
        "region": "Europa",
        "sector": "Educación Superior",
        "tipo": "cooperación_internacional",
        "estado": "abierta",
        "fecha_publicacion": datetime(2025, 11, 20),
        "fecha_apertura": datetime(2026, 1, 5),
        "fecha_cierre": datetime(2026, 3, 25),
        "monto_minimo": 100000,
        "monto_maximo": 400000,
        "moneda": "EUR",
        "url_fuente": "https://ec.europa.eu/programmes/erasmus-plus/opportunities/ka2-2026",
        "requisitos": "Consorcio de al menos 3 instituciones de educación superior de 3 países del programa.",
        "beneficiarios": "Universidades y centros de formación en Europa y países asociados.",
        "tags": "Erasmus+,educación,cooperación,universidades,Europa",
        "fuente_scraping": "EU Funding & Tenders",
    },
]


async def seed():
    await init_db()
    async with async_session() as db:
        for item in SAMPLE_DATA:
            content = f"{item['titulo']}{item['url_fuente']}{item['entidad']}"
            item["hash_contenido"] = generate_hash(content)
            item["activa"] = True
            conv = Convocatoria(**item)
            db.add(conv)
        await db.commit()
        print(f"Seeded {len(SAMPLE_DATA)} sample convocatorias successfully!")


if __name__ == "__main__":
    asyncio.run(seed())
