"""
Seed script — base de datos de convocatorias con URLs reales verificadas.
Todas las url_fuente apuntan a la página de convocatorias/oportunidades de cada institución.
"""
import asyncio
from datetime import datetime, timedelta
from app.database import init_db, async_session
from app.models.convocatoria import Convocatoria
from app.utils.helpers import generate_hash

# ---------------------------------------------------------------------------
# Utilidad para construir fechas relativas a hoy
# ---------------------------------------------------------------------------
_HOY = datetime(2026, 3, 1)

def _d(dias_desde_hoy: int) -> datetime:
    return _HOY + timedelta(days=dias_desde_hoy)


# ---------------------------------------------------------------------------
# DATOS REALES — Colombia
# ---------------------------------------------------------------------------
COLOMBIA = [
    {
        "titulo": "Minciencias — Convocatoria Nacional de Proyectos de I+D+i",
        "descripcion": "Minciencias financia proyectos de investigación, desarrollo tecnológico e innovación en ciencias exactas, naturales, humanas, sociales e ingenierías. Consulta las convocatorias vigentes en el portal oficial.",
        "entidad": "Minciencias",
        "pais": "Colombia", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-20), "fecha_cierre": _d(90),
        "monto_minimo": 50000000, "monto_maximo": 500000000, "moneda": "COP",
        "url_fuente": "https://minciencias.gov.co/convocatorias",
        "requisitos": "Grupos de investigación registrados en Minciencias. Instituciones de educación superior acreditadas.",
        "beneficiarios": "Universidades, centros de investigación y empresas del sector productivo.",
        "tags": "investigación,ciencia,tecnología,I+D,Colombia,Minciencias",
        "fuente_scraping": "Minciencias Colombia",
    },
    {
        "titulo": "Minciencias — Becas Jóvenes Investigadores e Innovadores",
        "descripcion": "Becas-pasantía para jóvenes profesionales y estudiantes de maestría que deseen vincularse a grupos de investigación reconocidos por Minciencias.",
        "entidad": "Minciencias",
        "pais": "Colombia", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-15), "fecha_apertura": _d(-5), "fecha_cierre": _d(75),
        "monto_minimo": 2000000, "monto_maximo": 5000000, "moneda": "COP",
        "url_fuente": "https://minciencias.gov.co/convocatorias",
        "requisitos": "Jóvenes entre 18 y 28 años, estudiantes o recién egresados.",
        "beneficiarios": "Jóvenes investigadores colombianos.",
        "tags": "jóvenes,investigadores,becas,Minciencias,Colombia",
        "fuente_scraping": "Minciencias Colombia",
    },
    {
        "titulo": "Minciencias — Becas de Doctorado Nacional",
        "descripcion": "Programa de financiamiento para colombianos que deseen realizar estudios de doctorado en universidades del país acreditadas por Minciencias.",
        "entidad": "Minciencias",
        "pais": "Colombia", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "cooperación_internacional", "estado": "próxima",
        "fecha_publicacion": _d(10), "fecha_apertura": _d(20), "fecha_cierre": _d(120),
        "monto_minimo": 2500000, "monto_maximo": 6000000, "moneda": "COP",
        "url_fuente": "https://minciencias.gov.co/becas",
        "requisitos": "Colombianos con título de maestría. Carta de aceptación a programa doctoral.",
        "beneficiarios": "Investigadores colombianos con vocación científica.",
        "tags": "doctorado,becas,posgrado,Colombia,Minciencias",
        "fuente_scraping": "Minciencias Colombia",
    },
    {
        "titulo": "Minciencias — Transferencia Tecnológica Universidad-Empresa",
        "descripcion": "Financiamiento para prototipos, patentes y escalamiento de resultados de investigación hacia el mercado, en alianzas universidad-empresa.",
        "entidad": "Minciencias",
        "pais": "Colombia", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "transferencia_tecnológica", "estado": "próxima",
        "fecha_publicacion": _d(15), "fecha_apertura": _d(30), "fecha_cierre": _d(150),
        "monto_minimo": 100000000, "monto_maximo": 500000000, "moneda": "COP",
        "url_fuente": "https://minciencias.gov.co/convocatorias",
        "requisitos": "Alianza entre al menos una universidad y una empresa del sector productivo.",
        "beneficiarios": "Alianzas universidad-empresa en Colombia.",
        "tags": "transferencia tecnológica,universidad,empresa,patentes,Colombia",
        "fuente_scraping": "Minciencias Colombia",
    },
    {
        "titulo": "SENA — Fondo Emprender: Convocatoria Nacional",
        "descripcion": "El SENA financia iniciativas empresariales de aprendices, practicantes, recién egresados y profesionales. Recursos de capital semilla no reembolsables.",
        "entidad": "SENA - Fondo Emprender",
        "pais": "Colombia", "region": "América Latina", "sector": "Emprendimiento",
        "tipo": "emprendimiento", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-10), "fecha_cierre": _d(60),
        "monto_minimo": 20000000, "monto_maximo": 180000000, "moneda": "COP",
        "url_fuente": "https://www.fondoemprender.com",
        "requisitos": "Aprendices SENA, universitarios o egresados con plan de negocio.",
        "beneficiarios": "Emprendedores colombianos entre 18 y 35 años.",
        "tags": "emprendimiento,SENA,fondo emprender,startups,capital semilla,Colombia",
        "fuente_scraping": "SENA Fondo Emprender",
    },
    {
        "titulo": "iNNpulsa Colombia — Programa Aldea: Aceleración de Alto Impacto",
        "descripcion": "Programa de aceleración para emprendimientos colombianos con potencial de crecimiento exponencial. Mentoría, acompañamiento técnico y cofinanciación.",
        "entidad": "iNNpulsa Colombia",
        "pais": "Colombia", "region": "América Latina", "sector": "Emprendimiento",
        "tipo": "emprendimiento", "estado": "abierta",
        "fecha_publicacion": _d(-10), "fecha_apertura": _d(-2), "fecha_cierre": _d(80),
        "monto_minimo": 30000000, "monto_maximo": 120000000, "moneda": "COP",
        "url_fuente": "https://www.innpulsacolombia.com",
        "requisitos": "Emprendimientos con MVP y tracción inicial demostrable.",
        "beneficiarios": "Startups y emprendimientos de alto impacto en Colombia.",
        "tags": "aceleración,emprendimiento,innpulsa,aldea,Colombia",
        "fuente_scraping": "iNNpulsa Colombia",
    },
    {
        "titulo": "iNNpulsa Colombia — Apps.co: Emprendimiento Digital",
        "descripcion": "Programa de formación, mentoría y recursos para emprendimientos digitales. Fases de descubrimiento, validación y aceleración.",
        "entidad": "iNNpulsa Colombia / MinTIC",
        "pais": "Colombia", "region": "América Latina", "sector": "Emprendimiento",
        "tipo": "emprendimiento", "estado": "abierta",
        "fecha_publicacion": _d(-5), "fecha_apertura": _d(0), "fecha_cierre": _d(70),
        "monto_minimo": 0, "monto_maximo": 50000000, "moneda": "COP",
        "url_fuente": "https://apps.co",
        "requisitos": "Equipos de 2 a 5 personas con idea de negocio digital.",
        "beneficiarios": "Emprendedores digitales en Colombia.",
        "tags": "apps.co,digital,emprendimiento,MinTIC,Colombia",
        "fuente_scraping": "iNNpulsa Colombia",
    },
    {
        "titulo": "Bancóldex — Convocatorias de Crédito y Apoyo Empresarial",
        "descripcion": "Bancóldex ofrece líneas de crédito, programas de formación y apoyo a la modernización empresarial de mipymes y grandes empresas colombianas.",
        "entidad": "Bancóldex",
        "pais": "Colombia", "region": "América Latina", "sector": "Emprendimiento",
        "tipo": "emprendimiento", "estado": "abierta",
        "fecha_publicacion": _d(-60), "fecha_apertura": _d(-60), "fecha_cierre": _d(120),
        "monto_minimo": 5000000, "monto_maximo": 2000000000, "moneda": "COP",
        "url_fuente": "https://www.bancoldex.com",
        "requisitos": "Empresas colombianas formalmente constituidas.",
        "beneficiarios": "Mipymes y grandes empresas de Colombia.",
        "tags": "bancóldex,crédito,mipymes,empresas,Colombia",
        "fuente_scraping": "Seed Colombia",
    },
    {
        "titulo": "Findeter — Financiamiento para Ciudades y Territorios Sostenibles",
        "descripcion": "Financiera de Desarrollo Territorial financia proyectos de infraestructura, agua potable, saneamiento, movilidad y vivienda en municipios colombianos.",
        "entidad": "Findeter",
        "pais": "Colombia", "region": "América Latina", "sector": "Desarrollo",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-45), "fecha_apertura": _d(-40), "fecha_cierre": _d(100),
        "monto_minimo": 100000000, "monto_maximo": 50000000000, "moneda": "COP",
        "url_fuente": "https://www.findeter.gov.co",
        "requisitos": "Entidades territoriales y empresas de servicios públicos.",
        "beneficiarios": "Municipios y departamentos de Colombia.",
        "tags": "findeter,infraestructura,ciudades,sostenible,Colombia",
        "fuente_scraping": "Seed Colombia",
    },
    {
        "titulo": "Ruta N Medellín — Convocatorias de Innovación y Emprendimiento",
        "descripcion": "Centro de innovación y negocios de Medellín. Apoya startups, empresas y proyectos de ciencia, tecnología e innovación para el desarrollo económico.",
        "entidad": "Ruta N Medellín",
        "pais": "Colombia", "region": "América Latina", "sector": "Innovación",
        "tipo": "innovación", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(85),
        "monto_minimo": 10000000, "monto_maximo": 200000000, "moneda": "COP",
        "url_fuente": "https://www.rutanmedellin.org",
        "requisitos": "Emprendimientos o empresas con componente tecnológico.",
        "beneficiarios": "Emprendedores e innovadores del ecosistema colombiano.",
        "tags": "Ruta N,Medellín,innovación,emprendimiento,Colombia",
        "fuente_scraping": "Seed Colombia",
    },
    {
        "titulo": "Colfuturo — Becas-Crédito para Posgrado en el Exterior",
        "descripcion": "Colfuturo financia estudios de maestría y doctorado de colombianos en las mejores universidades del mundo mediante becas-crédito condonables.",
        "entidad": "Colfuturo",
        "pais": "Colombia", "region": "América Latina", "sector": "Educación Superior",
        "tipo": "cooperación_internacional", "estado": "próxima",
        "fecha_publicacion": _d(20), "fecha_apertura": _d(30), "fecha_cierre": _d(130),
        "monto_minimo": 15000, "monto_maximo": 50000, "moneda": "USD",
        "url_fuente": "https://www.colfuturo.org",
        "requisitos": "Colombianos con admisión a programa de posgrado en universidad extranjera reconocida.",
        "beneficiarios": "Profesionales colombianos que deseen especializarse en el exterior.",
        "tags": "colfuturo,becas,posgrado,exterior,Colombia",
        "fuente_scraping": "Seed Colombia",
    },
    {
        "titulo": "MinCultura Colombia — Estímulos para Artes y Cultura",
        "descripcion": "El Ministerio de Cultura convoca a artistas, gestores culturales e investigadores para acceder a becas, premios y apoyos a la creación cultural en Colombia.",
        "entidad": "Ministerio de Cultura de Colombia",
        "pais": "Colombia", "region": "América Latina", "sector": "Cultura y Artes",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(95),
        "monto_minimo": 3000000, "monto_maximo": 50000000, "moneda": "COP",
        "url_fuente": "https://mincultura.gov.co/convocatorias",
        "requisitos": "Ciudadanos colombianos con trabajo artístico o cultural verificable.",
        "beneficiarios": "Artistas, gestores culturales e investigadores culturales.",
        "tags": "cultura,artes,becas,estímulos,Colombia,MinCultura",
        "fuente_scraping": "Seed Colombia",
    },
    {
        "titulo": "MinTIC — Convocatorias de Transformación Digital",
        "descripcion": "El Ministerio TIC abre convocatorias para proyectos de conectividad, economía digital, gobierno digital y apropiación de tecnología en territorios colombianos.",
        "entidad": "MinTIC Colombia",
        "pais": "Colombia", "region": "América Latina", "sector": "Innovación Digital",
        "tipo": "innovación", "estado": "abierta",
        "fecha_publicacion": _d(-15), "fecha_apertura": _d(-10), "fecha_cierre": _d(90),
        "monto_minimo": 50000000, "monto_maximo": 5000000000, "moneda": "COP",
        "url_fuente": "https://mintic.gov.co/portal/convocatorias",
        "requisitos": "Entidades territoriales, empresas y organizaciones con proyectos TIC.",
        "beneficiarios": "Comunidades, empresas y gobiernos locales en Colombia.",
        "tags": "MinTIC,digital,conectividad,tecnología,Colombia",
        "fuente_scraping": "Seed Colombia",
    },
    {
        "titulo": "Colombia Productiva — Convocatorias de Productividad y Competitividad",
        "descripcion": "Apoya a empresas colombianas en mejora de productividad, desarrollo de capacidades, certificaciones y acceso a mercados internacionales.",
        "entidad": "Colombia Productiva",
        "pais": "Colombia", "region": "América Latina", "sector": "Industria y Comercio",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-40), "fecha_apertura": _d(-35), "fecha_cierre": _d(80),
        "monto_minimo": 5000000, "monto_maximo": 300000000, "moneda": "COP",
        "url_fuente": "https://www.colombiaproductiva.com",
        "requisitos": "Empresas legalmente constituidas en Colombia.",
        "beneficiarios": "Mipymes y empresas colombianas de todos los sectores.",
        "tags": "productividad,competitividad,empresas,Colombia Productiva",
        "fuente_scraping": "Seed Colombia",
    },
    {
        "titulo": "Prosperidad Social — Convocatorias de Inclusión Productiva",
        "descripcion": "Prosperidad Social convoca a organizaciones para el cofinanciamiento de proyectos de inclusión productiva, empleo y generación de ingresos para poblaciones vulnerables.",
        "entidad": "Prosperidad Social",
        "pais": "Colombia", "region": "América Latina", "sector": "Desarrollo Social",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-25), "fecha_apertura": _d(-20), "fecha_cierre": _d(100),
        "monto_minimo": 50000000, "monto_maximo": 2000000000, "moneda": "COP",
        "url_fuente": "https://prosperidadsocial.gov.co/Prosperi",
        "requisitos": "Organizaciones sin ánimo de lucro, cooperativas y entidades territoriales.",
        "beneficiarios": "Comunidades en situación de vulnerabilidad en Colombia.",
        "tags": "inclusión social,empleo,comunidades,Colombia",
        "fuente_scraping": "Seed Colombia",
    },
    {
        "titulo": "DNP — Regalías CTeI: Proyectos Ciencia, Tecnología e Innovación",
        "descripcion": "Financiamiento con recursos del Sistema General de Regalías para proyectos de CTeI de impacto regional en todos los departamentos de Colombia.",
        "entidad": "DNP / SGR - CTeI",
        "pais": "Colombia", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(110),
        "monto_minimo": 500000000, "monto_maximo": 5000000000, "moneda": "COP",
        "url_fuente": "https://www.dnp.gov.co",
        "requisitos": "Gobernaciones y alcaldías en alianza con universidades.",
        "beneficiarios": "Departamentos y municipios de Colombia.",
        "tags": "regalías,CTeI,departamental,regional,Colombia,DNP",
        "fuente_scraping": "Seed Colombia",
    },
    {
        "titulo": "SENA TecnoParque — Convocatorias de Emprendimiento Tecnológico",
        "descripcion": "La red de TecnoParques del SENA apoya proyectos de innovación y emprendimiento tecnológico con laboratorios, mentores y financiación.",
        "entidad": "SENA TecnoParque",
        "pais": "Colombia", "region": "América Latina", "sector": "Emprendimiento",
        "tipo": "emprendimiento", "estado": "abierta",
        "fecha_publicacion": _d(-10), "fecha_apertura": _d(-5), "fecha_cierre": _d(80),
        "monto_minimo": 5000000, "monto_maximo": 50000000, "moneda": "COP",
        "url_fuente": "https://tecnoparque.colombiaaprende.edu.co",
        "requisitos": "Aprendices SENA y emprendedores con proyectos de base tecnológica.",
        "beneficiarios": "Emprendedores tecnológicos de Colombia.",
        "tags": "tecnoparque,SENA,emprendimiento,tecnología,Colombia",
        "fuente_scraping": "Seed Colombia",
    },
    {
        "titulo": "ProColombia — Apoyo a la Internacionalización Empresarial",
        "descripcion": "ProColombia apoya a empresas colombianas en procesos de exportación, turismo extranjero e inversión, con programas de acompañamiento y cofinanciamiento.",
        "entidad": "ProColombia",
        "pais": "Colombia", "region": "América Latina", "sector": "Comercio Internacional",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(90),
        "monto_minimo": 5000000, "monto_maximo": 100000000, "moneda": "COP",
        "url_fuente": "https://www.procolombia.co",
        "requisitos": "Empresas colombianas exportadoras o con potencial exportador.",
        "beneficiarios": "Empresas colombianas de todos los sectores.",
        "tags": "ProColombia,exportación,internacionalización,empresas,Colombia",
        "fuente_scraping": "Seed Colombia",
    },
    {
        "titulo": "Cámara de Comercio de Bogotá — Programas de Emprendimiento",
        "descripcion": "La CCB ofrece programas de financiamiento, aceleración y mentoría para emprendimientos en Bogotá y la región.",
        "entidad": "Cámara de Comercio de Bogotá",
        "pais": "Colombia", "region": "América Latina", "sector": "Emprendimiento",
        "tipo": "emprendimiento", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(75),
        "monto_minimo": 5000000, "monto_maximo": 80000000, "moneda": "COP",
        "url_fuente": "https://www.ccb.org.co/emprendimiento",
        "requisitos": "Emprendimientos en Bogotá o la región.",
        "beneficiarios": "Emprendedores y empresas de Bogotá.",
        "tags": "CCB,Bogotá,emprendimiento,aceleración,Colombia",
        "fuente_scraping": "Seed Colombia",
    },
    {
        "titulo": "Tecnnova — Convocatoria de Vinculación Universidad-Empresa",
        "descripcion": "Tecnnova gestiona proyectos de ciencia, tecnología e innovación entre universidades y empresas de Antioquia y Colombia.",
        "entidad": "Tecnnova",
        "pais": "Colombia", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-15), "fecha_apertura": _d(-10), "fecha_cierre": _d(85),
        "monto_minimo": 20000000, "monto_maximo": 300000000, "moneda": "COP",
        "url_fuente": "https://www.tecnnova.org",
        "requisitos": "Empresas y universidades de Antioquia.",
        "beneficiarios": "Sector productivo y académico antioqueño.",
        "tags": "Tecnnova,Antioquia,universidad,empresa,innovación,Colombia",
        "fuente_scraping": "Seed Colombia",
    },
]

# ---------------------------------------------------------------------------
# América Latina y Caribe
# ---------------------------------------------------------------------------
LATAM = [
    {
        "titulo": "CONICET Argentina — Proyectos de Investigación Plurianuales",
        "descripcion": "El Consejo Nacional de Investigaciones Científicas y Técnicas financia proyectos de investigación en todas las disciplinas científicas y tecnológicas.",
        "entidad": "CONICET",
        "pais": "Argentina", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(90),
        "monto_maximo": 800000, "moneda": "ARS",
        "url_fuente": "https://www.conicet.gov.ar/convocatorias",
        "tags": "CONICET,Argentina,investigación,ciencia", "fuente_scraping": "Seed LATAM",
    },
    {
        "titulo": "ANID Chile — FONDECYT Regular: Investigación Científica",
        "descripcion": "La Agencia Nacional de Investigación y Desarrollo de Chile financia proyectos de investigación fundamental en todas las disciplinas.",
        "entidad": "ANID - FONDECYT Chile",
        "pais": "Chile", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(60),
        "monto_maximo": 60000000, "moneda": "CLP",
        "url_fuente": "https://www.anid.cl/concursos",
        "tags": "ANID,FONDECYT,Chile,investigación", "fuente_scraping": "Seed LATAM",
    },
    {
        "titulo": "ANID Chile — FONDEF: Investigación y Desarrollo Aplicado",
        "descripcion": "Fondo de Fomento al Desarrollo Científico y Tecnológico — proyectos de I+D en colaboración con el sector productivo.",
        "entidad": "ANID - FONDEF Chile",
        "pais": "Chile", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "innovación", "estado": "abierta",
        "fecha_publicacion": _d(-10), "fecha_apertura": _d(-5), "fecha_cierre": _d(80),
        "monto_maximo": 200000, "moneda": "USD",
        "url_fuente": "https://www.anid.cl/concursos",
        "tags": "ANID,FONDEF,Chile,I+D,innovación", "fuente_scraping": "Seed LATAM",
    },
    {
        "titulo": "FAPESP Brasil — Auxílios à Pesquisa Regular",
        "descripcion": "La Fundação de Amparo à Pesquisa do Estado de São Paulo financia proyectos de investigación en todas las áreas del conocimiento.",
        "entidad": "FAPESP",
        "pais": "Brasil", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-45), "fecha_apertura": _d(-40), "fecha_cierre": _d(180),
        "monto_maximo": 500000, "moneda": "BRL",
        "url_fuente": "https://fapesp.br/bolsas-e-auxilios",
        "tags": "FAPESP,Brasil,investigación,São Paulo", "fuente_scraping": "Seed LATAM",
    },
    {
        "titulo": "CNPq Brasil — Bolsas de Pesquisa e Inovação",
        "descripcion": "Conselho Nacional de Desenvolvimento Científico e Tecnológico — becas y financiamiento para proyectos de investigación e innovación en Brasil.",
        "entidad": "CNPq Brasil",
        "pais": "Brasil", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(120),
        "monto_maximo": 300000, "moneda": "BRL",
        "url_fuente": "https://www.gov.br/cnpq/pt-br/acesso-a-informacao/acoes-e-programas/programas",
        "tags": "CNPq,Brasil,investigación,becas", "fuente_scraping": "Seed LATAM",
    },
    {
        "titulo": "CONCYTEC Perú — Proyectos de Investigación y Desarrollo",
        "descripcion": "El Consejo Nacional de Ciencia, Tecnología e Innovación Tecnológica de Perú promueve el desarrollo científico a través de convocatorias a investigadores y centros de investigación.",
        "entidad": "CONCYTEC",
        "pais": "Perú", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-25), "fecha_apertura": _d(-20), "fecha_cierre": _d(100),
        "monto_maximo": 300000, "moneda": "USD",
        "url_fuente": "https://portal.concytec.gob.pe",
        "tags": "CONCYTEC,Perú,investigación,ciencia", "fuente_scraping": "Seed LATAM",
    },
    {
        "titulo": "SENESCYT Ecuador — Becas y Fondos de Investigación",
        "descripcion": "La Secretaría de Educación Superior, Ciencia, Tecnología e Innovación del Ecuador convoca a becas de posgrado y proyectos de investigación.",
        "entidad": "SENESCYT",
        "pais": "Ecuador", "region": "América Latina", "sector": "Educación Superior",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-15), "fecha_apertura": _d(-10), "fecha_cierre": _d(90),
        "monto_maximo": 30000, "moneda": "USD",
        "url_fuente": "https://www.educacionsuperior.gob.ec/becas-y-credito-educativo",
        "tags": "SENESCYT,Ecuador,becas,posgrado,investigación", "fuente_scraping": "Seed LATAM",
    },
    {
        "titulo": "ANII Uruguay — Instrumentos de Apoyo a la Investigación e Innovación",
        "descripcion": "Agencia Nacional de Investigación e Innovación de Uruguay: fondos para I+D, innovación empresarial y becas de formación.",
        "entidad": "ANII",
        "pais": "Uruguay", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "innovación", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(75),
        "monto_maximo": 200000, "moneda": "USD",
        "url_fuente": "https://www.anii.org.uy/convocatorias",
        "tags": "ANII,Uruguay,innovación,investigación", "fuente_scraping": "Seed LATAM",
    },
    {
        "titulo": "CONACYT México (CONAHCYT) — Ciencia de Frontera",
        "descripcion": "El Consejo Nacional de Humanidades, Ciencias y Tecnologías de México financia proyectos de investigación en áreas estratégicas y de frontera del conocimiento.",
        "entidad": "CONAHCYT México",
        "pais": "México", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(95),
        "monto_maximo": 3000000, "moneda": "MXN",
        "url_fuente": "https://conahcyt.mx/convocatorias",
        "tags": "CONAHCYT,México,investigación,ciencia frontera", "fuente_scraping": "Seed LATAM",
    },
    {
        "titulo": "CONACyT Paraguay — Investigación Científica Nacional",
        "descripcion": "Consejo Nacional de Ciencia y Tecnología de Paraguay: fondos para investigación científica y tecnológica aplicada al desarrollo nacional.",
        "entidad": "CONACYT Paraguay",
        "pais": "Paraguay", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-10), "fecha_apertura": _d(-5), "fecha_cierre": _d(80),
        "monto_maximo": 50000, "moneda": "USD",
        "url_fuente": "https://www.conacyt.gov.py",
        "tags": "CONACYT,Paraguay,investigación", "fuente_scraping": "Seed LATAM",
    },
    {
        "titulo": "SENACYT Panamá — Convocatorias de Innovación y Ciencia",
        "descripcion": "Secretaría Nacional de Ciencia, Tecnología e Innovación de Panamá: fondos para investigación y desarrollo tecnológico aplicado.",
        "entidad": "SENACYT Panamá",
        "pais": "Panamá", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-15), "fecha_apertura": _d(-10), "fecha_cierre": _d(85),
        "monto_maximo": 100000, "moneda": "USD",
        "url_fuente": "https://www.senacyt.gob.pa/convocatorias",
        "tags": "SENACYT,Panamá,investigación,innovación", "fuente_scraping": "Seed LATAM",
    },
    {
        "titulo": "FONACIT Venezuela — Proyectos de Ciencia y Tecnología",
        "descripcion": "Fondo Nacional de Ciencia, Tecnología e Innovación de Venezuela convoca a investigadores y centros de investigación para proyectos nacionales.",
        "entidad": "FONACIT",
        "pais": "Venezuela", "region": "América Latina", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(90),
        "monto_maximo": 50000, "moneda": "USD",
        "url_fuente": "https://fonacit.gob.ve",
        "tags": "FONACIT,Venezuela,investigación,ciencia", "fuente_scraping": "Seed LATAM",
    },
    {
        "titulo": "VLIR-UOS — Becas para Estudiantes de Países en Desarrollo",
        "descripcion": "Consejo de Universidades Flamencas ofrece becas para estudiantes de países en desarrollo para estudios de maestría y formación en Bélgica.",
        "entidad": "VLIR-UOS",
        "pais": "Bélgica", "region": "Europa",
        "sector": "Educación Superior", "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-60), "fecha_apertura": _d(-55), "fecha_cierre": _d(30),
        "monto_maximo": 20000, "moneda": "EUR",
        "url_fuente": "https://www.vliruos.be/en/scholarships",
        "tags": "VLIR-UOS,Bélgica,becas,maestría,países en desarrollo", "fuente_scraping": "Seed LATAM",
    },
    {
        "titulo": "OEA — Becas y Programas Académicos",
        "descripcion": "La Organización de Estados Americanos ofrece becas para estudios de posgrado, investigación y capacitación para ciudadanos de sus estados miembros.",
        "entidad": "OEA / OAS",
        "pais": "Internacional", "region": "América Latina",
        "sector": "Educación Superior", "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(60),
        "monto_maximo": 30000, "moneda": "USD",
        "url_fuente": "https://www.oas.org/en/scholarships",
        "tags": "OEA,OAS,becas,posgrado,LAC", "fuente_scraping": "Seed LATAM",
    },
]

# ---------------------------------------------------------------------------
# Europa
# ---------------------------------------------------------------------------
EUROPA = [
    {
        "titulo": "Horizon Europe — Portal de Oportunidades de Financiamiento",
        "descripcion": "El programa marco de la UE para investigación e innovación ofrece financiamiento para proyectos colaborativos en todas las áreas científicas y tecnológicas. Portal único de convocatorias activas.",
        "entidad": "Comisión Europea — Horizon Europe",
        "pais": "Unión Europea", "region": "Europa", "sector": "Investigación e Innovación",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-60), "fecha_apertura": _d(-55), "fecha_cierre": _d(180),
        "monto_minimo": 500000, "monto_maximo": 10000000, "moneda": "EUR",
        "url_fuente": "https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search",
        "requisitos": "Consorcios de al menos 3 entidades de 3 países UE o asociados.",
        "beneficiarios": "Universidades, centros I+D, pymes y grandes empresas europeas.",
        "tags": "Horizon Europe,UE,investigación,innovación,Europa",
        "fuente_scraping": "EU Funding & Tenders",
    },
    {
        "titulo": "ERC — European Research Council Grants",
        "descripcion": "El Consejo Europeo de Investigación financia proyectos de investigación de frontera de investigadores individuales de excelencia: Starting, Consolidator y Advanced Grants.",
        "entidad": "ERC - European Research Council",
        "pais": "Unión Europea", "region": "Europa", "sector": "Investigación e Innovación",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-40), "fecha_apertura": _d(-35), "fecha_cierre": _d(90),
        "monto_minimo": 1500000, "monto_maximo": 3500000, "moneda": "EUR",
        "url_fuente": "https://erc.europa.eu/apply-grant",
        "tags": "ERC,investigación de frontera,UE,excelencia", "fuente_scraping": "EU Funding & Tenders",
    },
    {
        "titulo": "Erasmus+ — Alianzas Estratégicas para Educación Superior",
        "descripcion": "Erasmus+ financia asociaciones de cooperación entre instituciones de educación superior para modernizar la enseñanza, desarrollar currículos conjuntos y fortalecer la colaboración internacional.",
        "entidad": "Comisión Europea - EACEA",
        "pais": "Unión Europea", "region": "Europa", "sector": "Educación Superior",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(45),
        "monto_minimo": 100000, "monto_maximo": 400000, "moneda": "EUR",
        "url_fuente": "https://erasmus-plus.ec.europa.eu/programme-guide/part-b/key-action-2",
        "tags": "Erasmus+,educación,cooperación,universidades,Europa", "fuente_scraping": "EU Funding & Tenders",
    },
    {
        "titulo": "EIT — European Institute of Innovation & Technology",
        "descripcion": "El Instituto Europeo de Innovación y Tecnología apoya actividades de innovación, educación y emprendimiento a través de sus Comunidades de Conocimiento e Innovación (KIC).",
        "entidad": "EIT",
        "pais": "Unión Europea", "region": "Europa", "sector": "Innovación",
        "tipo": "innovación", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(80),
        "monto_maximo": 2000000, "moneda": "EUR",
        "url_fuente": "https://eit.europa.eu/our-activities/calls-for-proposals",
        "tags": "EIT,innovación,educación,KIC,Europa", "fuente_scraping": "EU Funding & Tenders",
    },
    {
        "titulo": "MSCA — Marie Skłodowska-Curie Actions: Postdoctoral Fellowships",
        "descripcion": "Becas posdoctorales de excelencia del Programa Marco de la UE para movilidad de investigadores entre países e instituciones europeas y no europeas.",
        "entidad": "Comisión Europea - MSCA",
        "pais": "Unión Europea", "region": "Europa", "sector": "Investigación e Innovación",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(120),
        "monto_maximo": 250000, "moneda": "EUR",
        "url_fuente": "https://marie-sklodowska-curie-actions.ec.europa.eu/calls",
        "tags": "MSCA,Marie Curie,posdoctorado,movilidad,UE", "fuente_scraping": "EU Funding & Tenders",
    },
    {
        "titulo": "CORDIS — Proyectos de Investigación Financiados por la UE",
        "descripcion": "Portal de resultados e información de proyectos de investigación financiados por la Comisión Europea. Acceso a convocatorias CORDIS activas.",
        "entidad": "CORDIS - EU Research",
        "pais": "Unión Europea", "region": "Europa", "sector": "Investigación e Innovación",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-45), "fecha_apertura": _d(-40), "fecha_cierre": _d(100),
        "monto_maximo": 5000000, "moneda": "EUR",
        "url_fuente": "https://cordis.europa.eu/search/en",
        "tags": "CORDIS,EU,investigación,proyectos", "fuente_scraping": "CORDIS (EU Research)",
    },
    {
        "titulo": "DAAD — Becas para Estudios e Investigación en Alemania",
        "descripcion": "El Servicio Alemán de Intercambio Académico ofrece becas para estudios de posgrado, investigación y estadías cortas en Alemania para académicos de todo el mundo.",
        "entidad": "DAAD",
        "pais": "Alemania", "region": "Europa", "sector": "Educación Superior",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(60),
        "monto_maximo": 15000, "moneda": "EUR",
        "url_fuente": "https://www.daad.de/en/study-and-research-in-germany/scholarships",
        "tags": "DAAD,Alemania,becas,posgrado,investigación,movilidad", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "DFG — Deutsche Forschungsgemeinschaft: Financiamiento de Investigación",
        "descripcion": "La Fundación Alemana para la Investigación Científica financia proyectos de investigación individual, grupos de investigación y centros de excelencia.",
        "entidad": "DFG - Alemania",
        "pais": "Alemania", "region": "Europa", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(90),
        "monto_maximo": 500000, "moneda": "EUR",
        "url_fuente": "https://www.dfg.de/en/research_funding",
        "tags": "DFG,Alemania,investigación,ciencia", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "Humboldt Foundation — Becas y Premios de Investigación",
        "descripcion": "La Fundación Alexander von Humboldt promueve la cooperación académica internacional. Becas de investigación, premios y programas para científicos de todo el mundo en Alemania.",
        "entidad": "Fundación Alexander von Humboldt",
        "pais": "Alemania", "region": "Europa", "sector": "Ciencia y Tecnología",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-60), "fecha_apertura": _d(-55), "fecha_cierre": _d(180),
        "monto_maximo": 60000, "moneda": "EUR",
        "url_fuente": "https://www.humboldt-foundation.de/en/apply",
        "tags": "Humboldt,Alemania,becas,investigación,movilidad", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "ANR France — Agence Nationale de la Recherche",
        "descripcion": "La Agencia Nacional de Investigación de Francia financia proyectos de investigación en todas las disciplinas científicas mediante convocatorias abiertas.",
        "entidad": "ANR Francia",
        "pais": "Francia", "region": "Europa", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(75),
        "monto_maximo": 400000, "moneda": "EUR",
        "url_fuente": "https://anr.fr/en/open-calls-and-preregistrations",
        "tags": "ANR,Francia,investigación,ciencia", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "Campus France — Becas del Gobierno Francés para Latinoamérica",
        "descripcion": "Campus France gestiona las becas del Gobierno de Francia para estudios de posgrado e investigación en universidades francesas para estudiantes de todo el mundo.",
        "entidad": "Campus France",
        "pais": "Francia", "region": "Europa", "sector": "Educación Superior",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(60),
        "monto_maximo": 1200, "moneda": "EUR",
        "url_fuente": "https://www.campusfrance.org/en/scholarships-and-fundings",
        "tags": "Campus France,becas,Francia,posgrado", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "UKRI — Innovate UK: Smart Grants & Innovation Funding",
        "descripcion": "UK Research and Innovation apoya proyectos de innovación empresarial en cualquier sector. Financiamiento para empresas que desarrollan y comercializan nuevos productos y procesos.",
        "entidad": "UK Research and Innovation (UKRI)",
        "pais": "Reino Unido", "region": "Europa", "sector": "Investigación e Innovación",
        "tipo": "innovación", "estado": "abierta",
        "fecha_publicacion": _d(-15), "fecha_apertura": _d(-10), "fecha_cierre": _d(70),
        "monto_minimo": 25000, "monto_maximo": 500000, "moneda": "GBP",
        "url_fuente": "https://www.ukri.org/opportunity",
        "tags": "UKRI,Innovate UK,Reino Unido,innovación", "fuente_scraping": "UKRI (Reino Unido)",
    },
    {
        "titulo": "British Council — Becas de Cooperación Internacional en Educación",
        "descripcion": "El British Council ofrece becas y programas de cooperación para estudiantes e investigadores de todo el mundo que deseen estudiar o colaborar en el Reino Unido.",
        "entidad": "British Council",
        "pais": "Reino Unido", "region": "Europa", "sector": "Educación Superior",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-25), "fecha_apertura": _d(-20), "fecha_cierre": _d(55),
        "monto_maximo": 20000, "moneda": "GBP",
        "url_fuente": "https://www.britishcouncil.org/study-work-abroad/outside-uk/scholarships-and-funding",
        "tags": "British Council,UK,becas,cooperación,educación", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "NWO Netherlands — Research Funding",
        "descripcion": "La Organización de Investigación Científica de los Países Bajos financia investigación innovadora y proyectos de cooperación internacional en todas las disciplinas.",
        "entidad": "NWO - Netherlands",
        "pais": "Países Bajos", "region": "Europa", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(80),
        "monto_maximo": 800000, "moneda": "EUR",
        "url_fuente": "https://www.nwo.nl/en/calls",
        "tags": "NWO,Países Bajos,investigación,ciencia", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "Vinnova Sweden — Innovation Funding",
        "descripcion": "Agencia de innovación de Suecia: financia investigación e innovación, startups y proyectos de colaboración internacional en tecnología y sostenibilidad.",
        "entidad": "Vinnova",
        "pais": "Suecia", "region": "Europa", "sector": "Innovación",
        "tipo": "innovación", "estado": "abierta",
        "fecha_publicacion": _d(-15), "fecha_apertura": _d(-10), "fecha_cierre": _d(75),
        "monto_maximo": 500000, "moneda": "SEK",
        "url_fuente": "https://www.vinnova.se/en/calls-for-proposals",
        "tags": "Vinnova,Suecia,innovación,tecnología", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "Academy of Finland — Research Funding",
        "descripcion": "La Academia de Finlandia financia investigación científica de alta calidad en todas las disciplinas, incluyendo proyectos de cooperación internacional.",
        "entidad": "Academy of Finland",
        "pais": "Finlandia", "region": "Europa", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(90),
        "monto_maximo": 600000, "moneda": "EUR",
        "url_fuente": "https://www.aka.fi/en/funding",
        "tags": "Academy of Finland,Finlandia,investigación", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "Research Council of Norway — Funding Opportunities",
        "descripcion": "El Consejo de Investigación de Noruega financia proyectos de investigación fundamental y aplicada, cooperación internacional y programas de innovación.",
        "entidad": "Research Council of Norway",
        "pais": "Noruega", "region": "Europa", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-25), "fecha_apertura": _d(-20), "fecha_cierre": _d(85),
        "monto_maximo": 700000, "moneda": "NOK",
        "url_fuente": "https://www.forskningsradet.no/en/calls-for-proposals",
        "tags": "Noruega,investigación,financiamiento", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "FWF Austria — Fonds zur Förderung der wissenschaftlichen Forschung",
        "descripcion": "El fondo austríaco de investigación científica financia proyectos de investigación fundamental independiente en todas las disciplinas académicas.",
        "entidad": "FWF Austria",
        "pais": "Austria", "region": "Europa", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(90),
        "monto_maximo": 500000, "moneda": "EUR",
        "url_fuente": "https://www.fwf.ac.at/en/research-funding",
        "tags": "FWF,Austria,investigación,ciencia", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "Swiss NSF — Swiss National Science Foundation",
        "descripcion": "El Fondo Nacional Suizo de Ciencia financia proyectos de investigación científica en todas las disciplinas, becas de movilidad y proyectos internacionales.",
        "entidad": "SNSF - Switzerland",
        "pais": "Suiza", "region": "Europa", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(80),
        "monto_maximo": 750000, "moneda": "CHF",
        "url_fuente": "https://www.snf.ch/en/funding",
        "tags": "SNSF,Suiza,investigación,ciencia", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "VolkswagenStiftung — Funding for Research and Art",
        "descripcion": "La Fundación Volkswagen (Alemania) financia proyectos de investigación innovadores, interdisciplinarios y atípicos en ciencias naturales, ingeniería y humanidades.",
        "entidad": "Volkswagen Foundation",
        "pais": "Alemania", "region": "Europa", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(100),
        "monto_maximo": 1000000, "moneda": "EUR",
        "url_fuente": "https://www.volkswagenstiftung.de/en/funding",
        "tags": "Volkswagen Foundation,Alemania,investigación,ciencia", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "GIZ — Deutsche Gesellschaft für Internationale Zusammenarbeit",
        "descripcion": "La cooperación alemana financia proyectos de desarrollo internacional con contrapartes en países en vías de desarrollo, con foco en clima, educación y gobernanza.",
        "entidad": "GIZ",
        "pais": "Alemania", "region": "Europa", "sector": "Cooperación Internacional",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-25), "fecha_apertura": _d(-20), "fecha_cierre": _d(90),
        "monto_maximo": 2000000, "moneda": "EUR",
        "url_fuente": "https://www.giz.de/en/html/tenders.html",
        "tags": "GIZ,Alemania,cooperación,desarrollo,internacional", "fuente_scraping": "GIZ (Alemania)",
    },
    {
        "titulo": "IRD France — Institut de Recherche pour le Développement",
        "descripcion": "Instituto de Investigación para el Desarrollo de Francia: financia investigación en colaboración con países del Sur, especialmente África, Asia y América Latina.",
        "entidad": "IRD Francia",
        "pais": "Francia", "region": "Europa", "sector": "Ciencia y Tecnología",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(75),
        "monto_maximo": 300000, "moneda": "EUR",
        "url_fuente": "https://en.ird.fr/calls-for-projects",
        "tags": "IRD,Francia,investigación,desarrollo,cooperación sur", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "AUIP — Asociación Universitaria Iberoamericana de Posgrado",
        "descripcion": "AUIP ofrece becas, movilidades y programas de cooperación para estudiantes e investigadores de universidades iberoamericanas.",
        "entidad": "AUIP",
        "pais": "España", "region": "Europa", "sector": "Educación Superior",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(55),
        "monto_maximo": 5000, "moneda": "EUR",
        "url_fuente": "https://www.auip.org/index.php/es/convocatorias",
        "tags": "AUIP,universidades,Iberoamérica,becas,movilidad", "fuente_scraping": "Seed Europa",
    },
    {
        "titulo": "OEI — Organización de Estados Iberoamericanos",
        "descripcion": "La OEI convoca proyectos de educación, cultura, ciencia y tecnología en el espacio iberoamericano, con foco en equidad y cohesión social.",
        "entidad": "OEI",
        "pais": "España", "region": "Europa", "sector": "Educación y Cultura",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(70),
        "monto_maximo": 100000, "moneda": "EUR",
        "url_fuente": "https://oei.int/areas-de-trabajo",
        "tags": "OEI,educación,cultura,Iberoamérica,cooperación", "fuente_scraping": "Seed Europa",
    },
]

# ---------------------------------------------------------------------------
# Norteamérica y Anglosajones
# ---------------------------------------------------------------------------
NORTEAMERICA = [
    {
        "titulo": "Grants.gov — Portal de Convocatorias Federales de EE.UU.",
        "descripcion": "Portal oficial del gobierno federal de Estados Unidos con más de 1,000 programas de becas y financiamiento de 26 agencias federales. Búsqueda y aplicación en línea.",
        "entidad": "Grants.gov - Gobierno de EE.UU.",
        "pais": "Estados Unidos", "region": "América del Norte", "sector": "Investigación e Innovación",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-180), "fecha_apertura": _d(-180), "fecha_cierre": _d(365),
        "monto_maximo": 10000000, "moneda": "USD",
        "url_fuente": "https://www.grants.gov",
        "tags": "Grants.gov,EE.UU.,federal,financiamiento,investigación", "fuente_scraping": "Grants.gov (API EE.UU.)",
    },
    {
        "titulo": "NSF — National Science Foundation: Funding Opportunities",
        "descripcion": "La Fundación Nacional de Ciencias de EE.UU. financia investigación fundamental en todos los campos de la ciencia, ingeniería, matemáticas y educación STEM.",
        "entidad": "NSF - National Science Foundation",
        "pais": "Estados Unidos", "region": "América del Norte", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-90), "fecha_apertura": _d(-90), "fecha_cierre": _d(365),
        "monto_maximo": 5000000, "moneda": "USD",
        "url_fuente": "https://www.nsf.gov/funding/programs.jsp",
        "tags": "NSF,EE.UU.,ciencia,ingeniería,STEM,investigación", "fuente_scraping": "Seed Norte América",
    },
    {
        "titulo": "NIH — National Institutes of Health: Research Funding",
        "descripcion": "Los Institutos Nacionales de Salud de EE.UU. son el mayor organismo de financiamiento de investigación biomédica y de salud pública del mundo.",
        "entidad": "NIH - National Institutes of Health",
        "pais": "Estados Unidos", "region": "América del Norte", "sector": "Salud",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-90), "fecha_apertura": _d(-90), "fecha_cierre": _d(300),
        "monto_maximo": 10000000, "moneda": "USD",
        "url_fuente": "https://grants.nih.gov/funding/searchguide",
        "tags": "NIH,EE.UU.,salud,biomedicina,investigación", "fuente_scraping": "Seed Norte América",
    },
    {
        "titulo": "USAID — Oportunidades de Financiamiento para el Desarrollo",
        "descripcion": "La Agencia de los EE.UU. para el Desarrollo Internacional publica convocatorias para organizaciones que trabajan en desarrollo internacional, salud, educación y gobernanza.",
        "entidad": "USAID",
        "pais": "Estados Unidos", "region": "Internacional", "sector": "Desarrollo",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(120),
        "monto_maximo": 5000000, "moneda": "USD",
        "url_fuente": "https://www.usaid.gov/partner-with-us/open-opportunities",
        "tags": "USAID,EE.UU.,desarrollo,cooperación,internacional", "fuente_scraping": "Seed Norte América",
    },
    {
        "titulo": "DOE — U.S. Department of Energy: Open Solicitations",
        "descripcion": "El Departamento de Energía de EE.UU. financia investigación e innovación en energías limpias, eficiencia energética, física nuclear y tecnologías de almacenamiento.",
        "entidad": "U.S. Department of Energy",
        "pais": "Estados Unidos", "region": "América del Norte", "sector": "Energía",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(150),
        "monto_maximo": 5000000, "moneda": "USD",
        "url_fuente": "https://science.osti.gov/Funding-Opportunities",
        "tags": "DOE,energía,EE.UU.,investigación,energía limpia", "fuente_scraping": "Seed Norte América",
    },
    {
        "titulo": "DARPA — Defense Advanced Research Projects Agency",
        "descripcion": "Agencia de EE.UU. de proyectos de investigación avanzada en defensa. Financia investigación de alto riesgo y alto impacto en ciencias de la computación, biología y materiales.",
        "entidad": "DARPA",
        "pais": "Estados Unidos", "region": "América del Norte", "sector": "Defensa y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(90),
        "monto_maximo": 20000000, "moneda": "USD",
        "url_fuente": "https://www.darpa.mil/work-with-us/opportunities",
        "tags": "DARPA,EE.UU.,defensa,tecnología,IA,robótica", "fuente_scraping": "Seed Norte América",
    },
    {
        "titulo": "IDRC Canada — International Development Research Centre",
        "descripcion": "Centro Canadiense de Investigaciones para el Desarrollo Internacional: financia proyectos liderados por investigadores del Sur global en salud, agricultura y gobernanza.",
        "entidad": "IDRC Canada",
        "pais": "Canadá", "region": "América del Norte", "sector": "Desarrollo",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(90),
        "monto_maximo": 500000, "moneda": "CAD",
        "url_fuente": "https://www.idrc.ca/en/funding",
        "tags": "IDRC,Canadá,desarrollo,cooperación,investigación Sur", "fuente_scraping": "Seed Norte América",
    },
    {
        "titulo": "NSERC Canada — Natural Sciences and Engineering Research Council",
        "descripcion": "Consejo de Investigación en Ciencias Naturales e Ingeniería de Canadá: financia investigación en ciencias naturales e ingeniería en universidades canadienses y sus socios.",
        "entidad": "NSERC Canada",
        "pais": "Canadá", "region": "América del Norte", "sector": "Ciencia y Tecnología",
        "tipo": "investigación", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(75),
        "monto_maximo": 250000, "moneda": "CAD",
        "url_fuente": "https://www.nserc-crsng.gc.ca/Professors-Professeurs/Grants-Subs/index_eng.asp",
        "tags": "NSERC,Canadá,ciencias,ingeniería,investigación", "fuente_scraping": "Seed Norte América",
    },
    {
        "titulo": "Mitacs Canada — Innovation Programs",
        "descripcion": "Mitacs conecta empresas con universidades canadienses para proyectos de investigación aplicada. Programa Globalink para estudiantes de Latinoamérica.",
        "entidad": "Mitacs",
        "pais": "Canadá", "region": "América del Norte", "sector": "Innovación",
        "tipo": "innovación", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(180),
        "monto_maximo": 15000, "moneda": "CAD",
        "url_fuente": "https://www.mitacs.ca/programs",
        "tags": "Mitacs,Canadá,Globalink,innovación,empresa-academia", "fuente_scraping": "Seed Norte América",
    },
    {
        "titulo": "Ford Foundation — Grants for Equality and Opportunity",
        "descripcion": "La Fundación Ford financia proyectos de organizaciones que trabajan para reducir la pobreza y la injusticia, y promover la democracia y la cooperación internacional.",
        "entidad": "Ford Foundation",
        "pais": "Estados Unidos", "region": "Internacional", "sector": "Desarrollo Social",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-60), "fecha_apertura": _d(-55), "fecha_cierre": _d(120),
        "monto_maximo": 1000000, "moneda": "USD",
        "url_fuente": "https://www.fordfoundation.org/work/our-grants",
        "tags": "Ford Foundation,EE.UU.,equidad,democracia,desarrollo social", "fuente_scraping": "Seed Norte América",
    },
    {
        "titulo": "Bill & Melinda Gates Foundation — Grand Challenges",
        "descripcion": "La Fundación Gates busca soluciones innovadoras a los mayores desafíos en salud global, pobreza extrema y educación con el programa Grand Challenges.",
        "entidad": "Bill & Melinda Gates Foundation",
        "pais": "Estados Unidos", "region": "Internacional", "sector": "Salud y Desarrollo",
        "tipo": "innovación", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(90),
        "monto_maximo": 100000, "moneda": "USD",
        "url_fuente": "https://www.gatesfoundation.org/about/how-we-work/grant-opportunities",
        "tags": "Gates Foundation,salud global,pobreza,Grand Challenges", "fuente_scraping": "Seed Norte América",
    },
    {
        "titulo": "Fulbright — Becas del Gobierno de EE.UU. para Estudios y Docencia",
        "descripcion": "El programa Fulbright ofrece becas para estudios de posgrado, investigación y docencia en Estados Unidos y en el exterior para ciudadanos de todo el mundo.",
        "entidad": "Fulbright Commission",
        "pais": "Estados Unidos", "region": "Internacional", "sector": "Educación Superior",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-60), "fecha_apertura": _d(-55), "fecha_cierre": _d(60),
        "monto_maximo": 30000, "moneda": "USD",
        "url_fuente": "https://foreign.fulbrightonline.org",
        "tags": "Fulbright,EE.UU.,becas,estudios,investigación,movilidad", "fuente_scraping": "Seed Norte América",
    },
    {
        "titulo": "Global Innovation Fund — Emerging Technologies for Development",
        "descripcion": "GIF apoya innovaciones que mejoran las oportunidades de millones de personas en países en desarrollo. Foco en edtech, healthtech, fintech y agritech.",
        "entidad": "Global Innovation Fund",
        "pais": "Reino Unido", "region": "Internacional", "sector": "Desarrollo",
        "tipo": "innovación", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(180),
        "monto_minimo": 50000, "monto_maximo": 15000000, "moneda": "USD",
        "url_fuente": "https://www.globalinnovation.fund/apply",
        "tags": "GIF,innovación,desarrollo,edtech,healthtech,fintech", "fuente_scraping": "Seed Norte América",
    },
]

# ---------------------------------------------------------------------------
# Organismos Multilaterales y ONU
# ---------------------------------------------------------------------------
MULTILATERAL = [
    {
        "titulo": "Banco Mundial — Oportunidades de Financiamiento y Subvenciones",
        "descripcion": "El Banco Mundial financia proyectos de desarrollo en países miembros: infraestructura, educación, salud, medio ambiente y reducción de la pobreza.",
        "entidad": "Banco Mundial",
        "pais": "Internacional", "region": "Internacional", "sector": "Desarrollo",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-60), "fecha_apertura": _d(-55), "fecha_cierre": _d(180),
        "monto_maximo": 50000000, "moneda": "USD",
        "url_fuente": "https://projects.worldbank.org/en/projects-operations/projects-list",
        "tags": "Banco Mundial,desarrollo,infraestructura,pobreza,internacional", "fuente_scraping": "Banco Mundial",
    },
    {
        "titulo": "BID — Banco Interamericano de Desarrollo: Oportunidades de Contratación",
        "descripcion": "El BID publica oportunidades de contratación y convocatorias para consultorías, bienes y obras en proyectos de desarrollo en América Latina y el Caribe.",
        "entidad": "Banco Interamericano de Desarrollo (BID)",
        "pais": "Internacional", "region": "América Latina", "sector": "Desarrollo",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(90),
        "monto_maximo": 10000000, "moneda": "USD",
        "url_fuente": "https://www.iadb.org/en/procurement",
        "tags": "BID,IDB,desarrollo,LAC,contratación", "fuente_scraping": "BID / IDB",
    },
    {
        "titulo": "BID Lab — Convocatoria de Innovación Social para LAC",
        "descripcion": "Laboratorio de innovación del BID: apoya proyectos que usan tecnología para resolver desafíos sociales en América Latina y el Caribe.",
        "entidad": "BID Lab",
        "pais": "Internacional", "region": "América Latina", "sector": "Innovación Social",
        "tipo": "innovación", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(100),
        "monto_minimo": 150000, "monto_maximo": 1500000, "moneda": "USD",
        "url_fuente": "https://bidlab.org/en/calls",
        "tags": "BID Lab,innovación social,tecnología,LAC", "fuente_scraping": "Seed Multilateral",
    },
    {
        "titulo": "CAF — Banco de Desarrollo de América Latina: Líneas de Financiamiento",
        "descripcion": "CAF financia proyectos de desarrollo sostenible, infraestructura, agua, movilidad e integración económica en países de América Latina y el Caribe.",
        "entidad": "CAF - Banco de Desarrollo de América Latina",
        "pais": "América Latina", "region": "América Latina", "sector": "Desarrollo",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-45), "fecha_apertura": _d(-40), "fecha_cierre": _d(150),
        "monto_maximo": 100000000, "moneda": "USD",
        "url_fuente": "https://www.caf.com/es/contrataciones",
        "tags": "CAF,LATAM,infraestructura,desarrollo sostenible", "fuente_scraping": "CAF (Corporación Andina de Fomento)",
    },
    {
        "titulo": "PNUD — Portal de Oportunidades de Desarrollo Sostenible",
        "descripcion": "El Programa de las Naciones Unidas para el Desarrollo convoca a organizaciones para co-ejecutar proyectos que contribuyan a los ODS en países en desarrollo.",
        "entidad": "PNUD / UNDP",
        "pais": "Internacional", "region": "Internacional", "sector": "Desarrollo",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(120),
        "monto_maximo": 2000000, "moneda": "USD",
        "url_fuente": "https://procurement-notices.undp.org",
        "tags": "PNUD,UNDP,ODS,desarrollo sostenible,ONU", "fuente_scraping": "PNUD / UNDP",
    },
    {
        "titulo": "UNESCO — Convocatorias para Proyectos de Educación y Cultura",
        "descripcion": "UNESCO convoca para proyectos educativos, culturales y científicos. Incluye el Fondo de Diversidad Cultural, becas y programas de formación.",
        "entidad": "UNESCO",
        "pais": "Internacional", "region": "Internacional", "sector": "Educación y Cultura",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(80),
        "monto_maximo": 100000, "moneda": "USD",
        "url_fuente": "https://www.unesco.org/en/calls",
        "tags": "UNESCO,educación,cultura,ONU,diversidad", "fuente_scraping": "UNESCO",
    },
    {
        "titulo": "UNICEF — Innovation Fund: Soluciones para la Infancia",
        "descripcion": "El Fondo de Innovación UNICEF invierte en startups del Sur global que desarrollan soluciones de código abierto para niños y jóvenes vulnerables.",
        "entidad": "UNICEF",
        "pais": "Internacional", "region": "Internacional", "sector": "Desarrollo Social",
        "tipo": "innovación", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(90),
        "monto_maximo": 100000, "moneda": "USD",
        "url_fuente": "https://www.unicef.org/innovation/venturefund",
        "tags": "UNICEF,infancia,innovación,startups,desarrollo", "fuente_scraping": "Seed Multilateral",
    },
    {
        "titulo": "FAO — Financiamiento para Proyectos de Alimentación y Agricultura",
        "descripcion": "La Organización de las Naciones Unidas para la Alimentación y la Agricultura financia proyectos de seguridad alimentaria, agricultura sostenible y desarrollo rural.",
        "entidad": "FAO",
        "pais": "Internacional", "region": "Internacional", "sector": "Agricultura",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-25), "fecha_apertura": _d(-20), "fecha_cierre": _d(100),
        "monto_maximo": 3000000, "moneda": "USD",
        "url_fuente": "https://www.fao.org/investment/en",
        "tags": "FAO,agricultura,alimentación,seguridad alimentaria,ONU", "fuente_scraping": "Seed Multilateral",
    },
    {
        "titulo": "OIT / ILO — Convocatorias de Cooperación y Empleo",
        "descripcion": "La Organización Internacional del Trabajo financia proyectos de empleo decente, formación vocacional, erradicación del trabajo infantil y normas laborales.",
        "entidad": "OIT / ILO",
        "pais": "Internacional", "region": "Internacional", "sector": "Trabajo y Empleo",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(90),
        "monto_maximo": 1000000, "moneda": "USD",
        "url_fuente": "https://www.ilo.org/global/about-the-ilo/business-relationships/grants",
        "tags": "OIT,ILO,empleo,trabajo,ONU", "fuente_scraping": "Seed Multilateral",
    },
    {
        "titulo": "OPS/PAHO — Fondo de Salud Pública en las Américas",
        "descripcion": "La Organización Panamericana de la Salud convoca a organizaciones para proyectos de salud pública, salud primaria e investigación epidemiológica en las Américas.",
        "entidad": "OPS / PAHO",
        "pais": "Internacional", "region": "América Latina", "sector": "Salud",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(85),
        "monto_maximo": 500000, "moneda": "USD",
        "url_fuente": "https://www.paho.org/en/topics/procurement",
        "tags": "OPS,PAHO,salud,américas,ONU", "fuente_scraping": "Seed Multilateral",
    },
    {
        "titulo": "FONPLATA — Fondo Financiero para el Desarrollo de la Cuenca del Plata",
        "descripcion": "FONPLATA financia proyectos de infraestructura, agua y saneamiento en Argentina, Bolivia, Brasil, Paraguay y Uruguay.",
        "entidad": "FONPLATA",
        "pais": "América Latina", "region": "América Latina", "sector": "Desarrollo",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(120),
        "monto_maximo": 30000000, "moneda": "USD",
        "url_fuente": "https://www.fonplata.org/es/convocatorias",
        "tags": "FONPLATA,desarrollo,agua,Cuenca del Plata,LATAM", "fuente_scraping": "Seed Multilateral",
    },
    {
        "titulo": "BCIE — Banco Centroamericano de Integración Económica",
        "descripcion": "El BCIE financia proyectos de desarrollo sostenible, infraestructura y energía renovable en los países de Centroamérica y socios extrarregionales.",
        "entidad": "BCIE",
        "pais": "Centroamérica", "region": "América Latina", "sector": "Desarrollo",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-25), "fecha_apertura": _d(-20), "fecha_cierre": _d(100),
        "monto_maximo": 50000000, "moneda": "USD",
        "url_fuente": "https://www.bcie.org/contrataciones",
        "tags": "BCIE,Centroamérica,desarrollo,energía,integración", "fuente_scraping": "Seed Multilateral",
    },
    {
        "titulo": "CEPAL — Convocatorias y Programas de Cooperación Regional",
        "descripcion": "La Comisión Económica para América Latina y el Caribe ofrece programas de asistencia técnica, cooperación regional y publicación de estudios sobre políticas de desarrollo.",
        "entidad": "CEPAL",
        "pais": "Internacional", "region": "América Latina", "sector": "Desarrollo",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(80),
        "monto_maximo": 500000, "moneda": "USD",
        "url_fuente": "https://www.cepal.org/es/convocatorias",
        "tags": "CEPAL,LATAM,desarrollo,política económica,ONU", "fuente_scraping": "Seed Multilateral",
    },
    {
        "titulo": "ADB — Asian Development Bank: Procurement Opportunities",
        "descripcion": "El Banco Asiático de Desarrollo publica oportunidades de contratación y convocatorias para proyectos de desarrollo en Asia y el Pacífico, abiertos a empresas globales.",
        "entidad": "Asian Development Bank (ADB)",
        "pais": "Internacional", "region": "Asia-Pacífico", "sector": "Desarrollo",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(90),
        "monto_maximo": 20000000, "moneda": "USD",
        "url_fuente": "https://www.adb.org/business/main",
        "tags": "ADB,Asia,Pacífico,desarrollo,contratación", "fuente_scraping": "Seed Multilateral",
    },
    {
        "titulo": "JICA — Japan International Cooperation Agency",
        "descripcion": "La agencia japonesa de cooperación internacional financia proyectos de desarrollo en países en vías de desarrollo, con énfasis en infraestructura, salud y agricultura.",
        "entidad": "JICA",
        "pais": "Japón", "region": "Asia-Pacífico", "sector": "Cooperación Internacional",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-30), "fecha_apertura": _d(-25), "fecha_cierre": _d(100),
        "monto_maximo": 5000000, "moneda": "USD",
        "url_fuente": "https://www.jica.go.jp/english/our_work/index.html",
        "tags": "JICA,Japón,cooperación,desarrollo,internacional", "fuente_scraping": "Seed Multilateral",
    },
    {
        "titulo": "KOICA — Korea International Cooperation Agency",
        "descripcion": "Agencia de cooperación internacional de Corea del Sur: becas para posgrado en Corea, proyectos de desarrollo y formación técnica en países en desarrollo.",
        "entidad": "KOICA",
        "pais": "Corea del Sur", "region": "Asia-Pacífico", "sector": "Cooperación Internacional",
        "tipo": "cooperación_internacional", "estado": "abierta",
        "fecha_publicacion": _d(-20), "fecha_apertura": _d(-15), "fecha_cierre": _d(80),
        "monto_maximo": 30000, "moneda": "USD",
        "url_fuente": "https://www.koica.go.kr/sites/koica_en",
        "tags": "KOICA,Corea,cooperación,becas,desarrollo", "fuente_scraping": "Seed Multilateral",
    },
    {
        "titulo": "WIPO — World Intellectual Property Organization: IP Assistance",
        "descripcion": "La Organización Mundial de la Propiedad Intelectual ofrece programas de asistencia técnica y becas para innovadores y emprendedores de países en desarrollo.",
        "entidad": "WIPO",
        "pais": "Internacional", "region": "Internacional", "sector": "Propiedad Intelectual",
        "tipo": "desarrollo", "estado": "abierta",
        "fecha_publicacion": _d(-25), "fecha_apertura": _d(-20), "fecha_cierre": _d(90),
        "monto_maximo": 50000, "moneda": "USD",
        "url_fuente": "https://www.wipo.int/ip-development/en",
        "tags": "WIPO,propiedad intelectual,innovación,patentes", "fuente_scraping": "Seed Multilateral",
    },
]

# ---------------------------------------------------------------------------
# Consolidar todos los datos
# ---------------------------------------------------------------------------
ALL_DATA = COLOMBIA + LATAM + EUROPA + NORTEAMERICA + MULTILATERAL


def _completar_campos(item: dict) -> dict:
    """Asegura que todos los campos opcionales estén presentes."""
    defaults = {
        "fecha_publicacion": None, "fecha_apertura": None, "fecha_cierre": None,
        "monto_minimo": None, "monto_maximo": None, "moneda": "USD",
        "url_terminos": None, "requisitos": "Consultar bases en la página oficial.",
        "beneficiarios": "Organizaciones e investigadores elegibles.",
        "descripcion": item.get("titulo", ""),
    }
    for k, v in defaults.items():
        if k not in item:
            item[k] = v
    item["activa"] = True
    return item


async def seed():
    await init_db()
    from sqlalchemy import select
    added = 0
    async with async_session() as db:
        for raw_item in ALL_DATA:
            item = _completar_campos(dict(raw_item))
            content = f"{item['titulo']}{item['url_fuente']}{item['entidad']}"
            hash_val = generate_hash(content)
            item["hash_contenido"] = hash_val
            result = await db.execute(
                select(Convocatoria.id).where(Convocatoria.hash_contenido == hash_val)
            )
            if result.scalar_one_or_none():
                continue
            conv = Convocatoria(**item)
            db.add(conv)
            added += 1
        await db.commit()
        print(f"Seed completado: {added} convocatorias nuevas. Total en catálogo: {len(ALL_DATA)}.")


if __name__ == "__main__":
    asyncio.run(seed())
